
wallpaper {
  monitor = DVI-I-1
  path = ~/Pictures/dual_monitor_wallpapers/left_earth_and_moon.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = ~/Pictures/dual_monitor_wallpapers/right_earth_and_moon.jpg
  fit_mode = cover
}

splash = false
ipc = off
