persistence = [
    "^(master|main|trunk)$",
    "^(develop|dev)$",
    "^feature.*$",
    "^release.*$",
    "^hotfix.*$",
    "^bugfix.*$",
]
order = [
    "^(master|main|trunk)$",
    "^(hotfix|release).*$",
    "^(develop|dev)$",
]

[terminal_colors]
matches = [
    [
    "^(master|main|trunk)$",
    ["bright_blue"],
],
    [
    "^(develop|dev)$",
    ["bright_yellow"],
],
    [
    "^(feature|fork/).*$",
    [
    "bright_magenta",
    "bright_cyan",
],
],
    [
    "^release.*$",
    ["bright_green"],
],
    [
    "^(bugfix|hotfix).*$",
    ["bright_red"],
],
    [
    "^tags/.*$",
    ["bright_green"],
],
]
unknown = ["white"]

[svg_colors]
matches = [
    [
    "^(master|main|trunk)$",
    ["blue"],
],
    [
    "^(develop|dev)$",
    ["orange"],
],
    [
    "^(feature|fork/).*$",
    [
    "purple",
    "turquoise",
],
],
    [
    "^release.*$",
    ["green"],
],
    [
    "^(bugfix|hotfix).*$",
    ["red"],
],
    [
    "^tags/.*$",
    ["green"],
],
]
unknown = ["gray"]
